### ISSUE TITLE
C++ Wrangle Sample ?

### ISSUE THREAD

**Issue by melMass** [captainhammy/Houdini-Toolbox#15]
Hi Captain,

First of all, a huge thanks for making this repository public, It helped me a lot to do my own setup.

I'm writing a C++ library based on HDK to use in other DCCs (I have a working integration in Nuke, Gaffer, Blender powered by HDK, LibGL(using Eigen) and PyBind11 for now)

Some parts of the HDK are still obscure and being able to live compile inside Houdini and seeing the result in the viewport would be a huge productivity boost.

Here comes my question, do you have a working sample of your C++ Wrangle? From all the integrations I've seen it seems to be the one who best fit my use case.

I tried to use it but did not really understand how it's written (first time I see this `PythonCook` magic) and so how to debug it.

Thanks

**Comment by melMass** [comment]
I think there is an issue in `ht.inline.eval_multiparm_instance`
it returns `\x10b=\x1a'#` when fed with:

```c
int numPoints(const GU_Detail *gdp)
{ 
return gdp->getNumPoints(); 
}
```

in the `function` parm.

**Comment by melMass** [comment]
Solved !! The node now works on my end !

I replaced the function here:
https://github.com/captainhammy/Houdini-Toolbox/blob/ad40b54c4538ff815e725134edac1daa959ac9c9/python/ht/inline/lib.py#L1954-L1969

By

```c
inlinecpp::BinaryString eval_multiparm_instance_string(OP_Node *node, const char *parm_name, int component_index, int index, int start_offset)
{
    fpreal                      t = CHgetEvalTime();
    int                         instance_index;

    const UT_StringRef          &name(parm_name);
    UT_String                   value;

    instance_index = index + start_offset;
    node->evalStringInst(name, &instance_index, value, component_index, t);

    addDependencyOnParm(node, name, instance_index, component_index);

    return value.toStdString();
}
```

**Comment by captainhammy** [comment]
Hey Mel, apologies for not seeing this sooner.  For some reason I haven't been getting notifications.

Would you be able to provide an example hip file of the issue you ran into with getting the bad values?  I'm not able to reproduce it on my end.  I'd like to try and figure out what happened so that I can add a test for it before making the change.

Thanks!

**Comment by melMass** [comment]
I think it’s an encoding issue maybe ?
The ´binary string’ type seems to handle it. 
Even the most simple example was not working.
If I can provide further feedback don’t hesitate.

**Comment by melMass** [comment]
Also I realize that I never specified that I was using OSX

**Comment by captainhammy** [comment]
It's converted to use a BinaryString now. Thanks for reporting!
