### ISSUE TITLE
Installing via packages method

### ISSUE THREAD

**Issue by GlennimusPrime** [captainhammy/Houdini-Toolbox#16]
Hello, I am trying to install the Houdini Toolbox via the packages method, but am a scripting novice.

I have managed to setup the packages method for things like Redshift before, but I have extremely limited knowledge of scripting.

I wonder if you have an example .json package file I could use to help me install the toolbox?

Thank you!

- Glenn

**Comment by Sachawech** [comment]
Hello!

I am also confused as to how you install this.

In the env file when I set HOUDINI_PATH to the "houdini" folder and the PYTHONPATH to the "python" folder, inside the Houdini-Toolbox folder, Houdini crashes at startup.

I am probably just doing it completely wrong haha

HOUDINI_PATH = ";C:/Program Files/Side Effects Software/Plugins/Houdini-Toolbox-master/houdini/;&"

PYTHONPATH = ";C:/Program Files/Side Effects Software/Plugins/Houdini-Toolbox-master/python/;&"

**Comment by captainhammy** [comment]
Oh man, sorry guys, I didn't see this.  Apologies.  I never seem to get notifications of issues.

I haven't really used the packages stuff before but give me a bit and I'll try to add one to replace the convoluted instructions.

**Comment by captainhammy** [comment]
So I've added a houdini-toolbox.json file which should set up the HOUDINI_PATH and PYTHONPATH vars for the package.

@Sachawech I'm not sure about your crash.  Could you try it again using the package file to set up the env and if it still crashes submit a new issue, ideally with a crash log?  Thanks!

**Comment by GlennimusPrime** [comment]
Hey no problem on the wait. Happy to check this out sometime over the next few weeks when work calms down a bit. Hopefully I can get this going. I'm still not 100% sure about what needs to be added or changed on either the .env or inside the new package .json, but will give it a go. Thanks!
